# Generated by Django 4.2.2 on 2023-06-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('link_map', models.URLField()),
            ],
            options={
                'verbose_name': 'Yer',
                'verbose_name_plural': 'Yerler',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.PositiveIntegerField()),
                ('baggage', models.PositiveIntegerField()),
                ('_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='transfer.place')),
                ('_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='transfer.place')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transferler',
            },
        ),
    ]
