# Generated by Django 4.2.2 on 2023-06-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='link_map',
            field=models.URLField(blank=True, null=True),
        ),
    ]
