# Generated by Django 4.2.2 on 2023-06-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_place_link_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('name',), 'verbose_name': 'Konum', 'verbose_name_plural': 'Konumlar'},
        ),
        migrations.AddField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=None, verbose_name='Tarih'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='price',
            field=models.PositiveIntegerField(default=None, verbose_name='Fiyat (TL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='time',
            field=models.TimeField(default=None, verbose_name='Saat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='link_map',
            field=models.URLField(blank=True, null=True, verbose_name='Konum linki'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Konum adı'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='transfer.place', verbose_name='Nereden'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='transfer.place', verbose_name='Nereye'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='baggage',
            field=models.PositiveIntegerField(verbose_name='Bagaj'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='pax',
            field=models.PositiveIntegerField(verbose_name='Kişi sayısı'),
        ),
    ]
