# Generated by Django 4.2.2 on 2023-06-27 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_transfer_paid_alter_transfer_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ('-paid', '-date', '-time', 'price'), 'verbose_name': 'Transfer', 'verbose_name_plural': 'Transferler'},
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='_from',
            new_name='rfrom',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='_to',
            new_name='rto',
        ),
    ]
