# Generated by Django 4.2.2 on 2023-06-27 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_alter_transfer_options_rename__from_transfer_rfrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='phone',
            field=models.CharField(default='123', max_length=20, verbose_name='Telefon numarası'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='proceed',
            field=models.BooleanField(default=False, verbose_name='İncelendi'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='rfrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='transfer.place', verbose_name='Nereden?'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='rto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='transfer.place', verbose_name='Nereye?'),
        ),
    ]
