# Generated by Django 4.2.2 on 2023-06-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_transfer_email_transfer_phone_transfer_proceed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
