# Generated by Django 4.2.2 on 2023-06-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_transfer_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma tarihi'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fiyat (USD)'),
        ),
    ]
