# Generated by Django 4.2.2 on 2023-06-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_alter_transfer_created_alter_transfer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Tur adı')),
                ('excerpt', models.TextField(verbose_name='Kısa açıklama')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='Tur süresi')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Turlar',
                'ordering': ('name', 'created'),
            },
        ),
    ]
