# Generated by Django 4.2.2 on 2023-06-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default=None, upload_to='transfer/tour/image/', verbose_name='Resim'),
            preserve_default=False,
        ),
    ]
