# Generated by Django 4.2.2 on 2023-06-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_tourcategory_tour_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Kategori etiketi')),
            ],
            options={
                'verbose_name': 'Tur etiketi',
                'verbose_name_plural': 'Tur etiketleri',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'ordering': ('name',), 'verbose_name': 'Tur kategorisi', 'verbose_name_plural': 'Tur kategorileri'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.tourcategory', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tags',
            field=models.ManyToManyField(blank=True, to='transfer.tourtag'),
        ),
    ]
