# Generated by Django 4.2.2 on 2023-06-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0012_tourtag_alter_tourcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('phone_whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='Kurumsal E-posta')),
                ('address', models.TextField(verbose_name='İş adresi')),
                ('address_link', models.TextField(verbose_name='İş adresi linki')),
            ],
            options={
                'verbose_name': 'Site ayarları',
                'verbose_name_plural': 'Site ayarları',
            },
        ),
    ]
