# Generated by Django 4.2.2 on 2023-06-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0013_companydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Değerlendirme'),
        ),
    ]
