# Generated by Django 4.2.2 on 2023-06-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0014_transfer_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferExtended',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transfer.transfer')),
                ('iata', models.CharField(max_length=10, verbose_name='Uçuş kodu')),
                ('first_name', models.CharField(max_length=20, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=20, verbose_name='Soyadı')),
                ('comment', models.TextField(verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Transfer (Gelişmiş)',
                'verbose_name_plural': 'Transferler (Gelişmiş)',
                'ordering': ('-paid', '-date', '-time', 'price'),
            },
            bases=('transfer.transfer', models.Model),
        ),
    ]
