# Generated by Django 4.2.2 on 2023-06-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0015_transferextended'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferextended',
            name='baggage_back',
            field=models.PositiveIntegerField(default=None, verbose_name='Bagaj'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferextended',
            name='date_back',
            field=models.DateField(default=None, verbose_name='Buluşma tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferextended',
            name='iata_back',
            field=models.CharField(default=None, max_length=10, verbose_name='Uçuş kodu (IATA)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferextended',
            name='pax_back',
            field=models.PositiveIntegerField(default=None, verbose_name='Kişi sayısı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferextended',
            name='time_back',
            field=models.TimeField(default=None, verbose_name='Buluşma saati'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(verbose_name='Buluşma tarihi'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.TimeField(verbose_name='Buluşma saati'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='iata',
            field=models.CharField(max_length=10, verbose_name='Uçuş kodu (IATA)'),
        ),
    ]
