# Generated by Django 4.2.2 on 2023-06-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0016_transferextended_baggage_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferextended',
            name='baggage_back',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bagaj'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='date_back',
            field=models.DateField(blank=True, verbose_name='Buluşma tarihi'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='iata_back',
            field=models.CharField(blank=True, max_length=10, verbose_name='Uçuş kodu (IATA)'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='pax_back',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kişi sayısı'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='time_back',
            field=models.TimeField(blank=True, null=True, verbose_name='Buluşma saati'),
        ),
    ]
