# Generated by Django 4.2.2 on 2023-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0017_alter_transferextended_baggage_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferextended',
            name='back',
            field=models.BooleanField(default=False, verbose_name='Ek geri dönüş'),
            preserve_default=False,
        ),
    ]
