# Generated by Django 4.2.2 on 2023-06-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0018_transferextended_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferextended',
            name='date_back',
            field=models.DateField(blank=True, null=True, verbose_name='Buluşma tarihi'),
        ),
    ]
