# Generated by Django 4.2.2 on 2023-06-29 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0020_transfer_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Ödeme yapıldı'),
        ),
    ]
