# Generated by Django 4.2.2 on 2023-06-29 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0022_remove_transfer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
