# Generated by Django 4.2.2 on 2023-07-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0024_companydata_phone_repr_alter_companydata_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Medya adı')),
                ('fa_icon', models.CharField(max_length=40, verbose_name='Ikon kodu (Font Awesome)')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Medya hesabı',
                'verbose_name_plural': 'Medya hesapları',
            },
        ),
        migrations.AddField(
            model_name='companydata',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Video linki'),
        ),
    ]
