# Generated by Django 4.2.2 on 2023-07-12 01:28

from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0027_weekday_tour_time_end_tour_time_start_tour_weekdays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekday',
            options={'ordering': ('-id',), 'verbose_name': 'Hafta günü', 'verbose_name_plural': 'Hafta günleri'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='weekdays',
            field=models.ManyToManyField(blank=True, to='transfer.weekday', verbose_name='Hafta günleri'),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Adı'),
        ),
    ]
