# Generated by Django 4.2.2 on 2023-07-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0028_alter_weekday_options_alter_tour_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
    ]
