# Generated by Django 4.2.2 on 2023-07-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0029_alter_tour_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Soru')),
                ('content', models.TextField(verbose_name='Cevap')),
            ],
            options={
                'verbose_name': 'Sıkça sorulan sorular',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=55, verbose_name='Adınız Soyadınız')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('description', models.TextField(verbose_name='Mesajınız')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Tarih ve saat')),
            ],
            options={
                'verbose_name': 'Talep, Şikayet',
                'verbose_name_plural': 'Talepler ve Şikayetler',
            },
        ),
    ]
