# Generated by Django 4.2.2 on 2023-07-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0030_faq_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='content',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='question',
        ),
    ]
