# Generated by Django 4.2.2 on 2023-07-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0031_rename_content_faq_answer_rename_title_faq_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Sıkça sorulan soru', 'verbose_name_plural': 'Sıkça sorulan sorular'},
        ),
        migrations.AddField(
            model_name='request',
            name='answered',
            field=models.BooleanField(default=True, verbose_name='Cevaplandı'),
            preserve_default=False,
        ),
    ]
