# Generated by Django 4.2.2 on 2023-07-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0032_alter_faq_options_request_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='uuid',
        ),
    ]
