# Generated by Django 4.2.2 on 2023-07-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0034_transferextended_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferextended',
            name='iata',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Uçuş kodu (IATA)'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='iata_back',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Uçuş kodu (IATA)'),
        ),
    ]
