# Generated by Django 4.2.2 on 2023-07-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0036_alter_transferextended_transfer_ptr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ('-date', '-time', 'proceed'), 'verbose_name': 'Transfer', 'verbose_name_plural': 'Transferler'},
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='done',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='rating',
        ),
        migrations.AddField(
            model_name='transferextended',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı'),
        ),
        migrations.AddField(
            model_name='transferextended',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Ödeme yapıldı'),
        ),
        migrations.AddField(
            model_name='transferextended',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fiyat (USD)'),
        ),
        migrations.AddField(
            model_name='transferextended',
            name='price_final',
            field=models.BooleanField(default=True, verbose_name='Fiyat sonmu?'),
        ),
        migrations.AddField(
            model_name='transferextended',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Değerlendirme'),
        ),
    ]
