# Generated by Django 4.2.2 on 2023-07-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0037_alter_transfer_options_remove_transfer_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(verbose_name='Your message'),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='request',
            name='full_name',
            field=models.CharField(max_length=55, verbose_name='Name surname'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='baggage',
            field=models.PositiveIntegerField(verbose_name='Baggage (kg)'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(verbose_name='Meeting date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='pax',
            field=models.PositiveIntegerField(verbose_name='Passengers'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='rfrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='transfer.place', verbose_name='From where?'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='rto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='transfer.place', verbose_name='To where?'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.TimeField(verbose_name='Meeting time'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='baggage_back',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Baggage (kg)'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='date_back',
            field=models.DateField(blank=True, null=True, verbose_name='Meeting date'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='iata',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Flight code (IATA)'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='iata_back',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Flight code (IATA)'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='pax_back',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Passengers'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='transferextended',
            name='time_back',
            field=models.TimeField(blank=True, null=True, verbose_name='Meeting time'),
        ),
    ]
