# Generated by Django 4.2.2 on 2023-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0038_alter_request_description_alter_request_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='tour',
            name='excerpt_de',
            field=models.TextField(null=True, verbose_name='Kısa açıklama'),
        ),
        migrations.AddField(
            model_name='tour',
            name='excerpt_en',
            field=models.TextField(null=True, verbose_name='Kısa açıklama'),
        ),
        migrations.AddField(
            model_name='tour',
            name='excerpt_ru',
            field=models.TextField(null=True, verbose_name='Kısa açıklama'),
        ),
        migrations.AddField(
            model_name='tour',
            name='excerpt_tr',
            field=models.TextField(null=True, verbose_name='Kısa açıklama'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_de',
            field=models.CharField(max_length=55, null=True, verbose_name='Tur adı'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Tur adı'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Tur adı'),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_tr',
            field=models.CharField(max_length=55, null=True, verbose_name='Tur adı'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_de',
            field=models.CharField(max_length=25, null=True, verbose_name='Kategori adı'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_en',
            field=models.CharField(max_length=25, null=True, verbose_name='Kategori adı'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_ru',
            field=models.CharField(max_length=25, null=True, verbose_name='Kategori adı'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='name_tr',
            field=models.CharField(max_length=25, null=True, verbose_name='Kategori adı'),
        ),
        migrations.AddField(
            model_name='tourtag',
            name='name_de',
            field=models.CharField(max_length=25, null=True, verbose_name='Kategori etiketi'),
        ),
        migrations.AddField(
            model_name='tourtag',
            name='name_en',
            field=models.CharField(max_length=25, null=True, verbose_name='Kategori etiketi'),
        ),
        migrations.AddField(
            model_name='tourtag',
            name='name_ru',
            field=models.CharField(max_length=25, null=True, verbose_name='Kategori etiketi'),
        ),
        migrations.AddField(
            model_name='tourtag',
            name='name_tr',
            field=models.CharField(max_length=25, null=True, verbose_name='Kategori etiketi'),
        ),
    ]
